### PR TITLE
Enhance middleware error reporting and logging without breaking changes

### LINKED ISSUE #619: middleware errors not logged
I have encountered situations that are unnecessarily difficult to debug because an error result from a middleware function is neither reported in the response body nor logged via tracing. For example, when the `attestation_middleware` returns `AttestationError::CouldNotFindSigner` the response just has status 500 with no body explaining what went wrong and there are no logs indicating an issue:
```
  2025-02-11T15:43:29.023335Z  INFO indexer_service_rs::metrics: Serving prometheus metrics, address: 0.0.0.0:7300
    at crates/service/src/metrics.rs:39

  2025-02-11T15:43:29.023364Z  INFO indexer_service_rs::service: Serving requests, address: 0.0.0.0:7601
    at crates/service/src/service.rs:123
```

Only after building the indexer-service from source with additional logging was I able to discover where in the pile of middleware something went wrong. There should be logs for middleware errors.

### PR DESCRIPTION
**Pull request by neithanmo**
This PR improves error reporting and logging in our middleware components(for attestation) without changing their existing behavior. It addresses issues where errors in middleware functions were neither reported in response bodies(just an error code) nor logged via tracing, making debugging unnecessarily difficult.

Key Changes
- Added structured error responses using `ErrorResponse` for better client feedback
- Implemented detailed tracing logs for error conditions, however, the current interface does not treat them as errors but as optional state changes. 
- Maintained backward compatibility with the existing middleware chain behavior
- Added explicit error/warning messages when signers are missing but attestation is requested

Fixes #619 - Error results from middleware functions not reported in logs or responses

### CODE REVIEW

**Review by suchapalaver — APPROVED** [review]
Nice! I take it this came out of the experience of working on testing patterns?

File: crates/service/src/middleware/attestation.rs [hunk 1]
```diff
@@ -93,12 +98,14 @@ impl StatusCodeExt for AttestationError {
 
 impl IntoResponse for AttestationError {
     fn into_response(self) -> Response {
-        self.status_code().into_response()
+        tracing::error!("Attestation error: {}", self);
```
Comment (TypeLevelConsoli) [inline crates/service/src/middleware/attestation.rs:101]:
```suggestion
        tracing::error!(error=self, "Attestation error");
```

**Review by TypeLevelConsoli — CHANGES_REQUESTED** [review]
great, I'm all in for structured errors

File: crates/service/src/middleware/attestation_signer.rs [hunk 2]
```diff
@@ -30,6 +30,12 @@ pub async fn signer_middleware(
     if let Some(Allocation(allocation_id)) = request.extensions().get::<Allocation>() {
         if let Some(signer) = state.attestation_signers.borrow().get(allocation_id) {
             request.extensions_mut().insert(signer.clone());
+        } else {
+            // Just log this case which is silently passed through next middleware
+            tracing::warn!(
+                "No attestation signer found for allocation {}",
+                allocation_id
+            );
```
[the remark this answers is not in the document]
Comment (TypeLevelConsoli) [reply crates/service/src/middleware/attestation_signer.rs:38]: for example, the current code will create a tracing event such as:

`2025-03-20T21:04:49.336978Z  WARN foo: No attestation signer found for allocation 123`

while structured params will give us:

`2025-03-20T21:05:10.407913Z  WARN foo: No attestation signer found for allocation allocation_id=123`

and so we can filter for both the message or a specific allocation_id

**Comment by neithanmo** [comment]
> great, I'm all in for structured errors

Thanks! @TypeLevelConsoli for suggestion, indeed, that way is clearer

File: crates/service/src/middleware/attestation_signer.rs [hunk 3]
```diff
@@ -30,6 +30,11 @@ pub async fn signer_middleware(
     if let Some(Allocation(allocation_id)) = request.extensions().get::<Allocation>() {
         if let Some(signer) = state.attestation_signers.borrow().get(allocation_id) {
             request.extensions_mut().insert(signer.clone());
+        } else {
+            // Just log this case which is silently passed through next middleware
+            tracing::warn!(warn=%allocation_id,
```
Comment (TypeLevelConsoli) [inline crates/service/src/middleware/attestation_signer.rs:35]: having the field named `warn` is not very helpful, instead, we should log it as `allocation_id` for better context

```suggestion
            tracing::warn!(allocation_id,
```

**Review by TypeLevelConsoli — CHANGES_REQUESTED** [review]

**Review by TypeLevelConsoli — APPROVED** [review]
