### PR TITLE
fix: Accept config to be through file or env vars

### LINKED ISSUE #337: Remove requirement for config file
**Problem statement**
It's possible to provide all config fields via environment variables, so we shouldn't require people to provide a file if they have all required config values.

### PR DESCRIPTION
**Pull request by carlosvdr**
fixes #337

### CODE REVIEW

**Comment by carlosvdr** [comment]
So I didnt added it, as in the validation it should fail so didnt saw a reason to add it.

But maybe also add to first validate the env vars, and if they are not all okay to error out a file name is alaso required?

File: config/src/config.rs [hunk 1]
```diff
@@ -68,12 +68,16 @@ impl ConfigPrefix {
 }
 
 impl Config {
-    pub fn parse(prefix: ConfigPrefix, filename: &PathBuf) -> Result<Self, String> {
+    pub fn parse(prefix: ConfigPrefix, filename: &Option<PathBuf>) -> Result<Self, String> {
```
Comment (gusinacio) [inline config/src/config.rs:71]: Almost always it's not a good idea to pass a reference to an Option. In case you want a reference, you want to pass an Option to a reference.

`&Option<T>` -> `Option<&T>`.

File: service/src/service.rs [hunk 2]
```diff
@@ -133,7 +133,7 @@ pub async fn run() -> anyhow::Result<()> {
         MainConfig::parse(indexer_config::ConfigPrefix::Service, &cli.config).map_err(|e| {
             error!(
                 "Invalid configuration file `{}`: {}",
-                cli.config.display(),
+                cli.config.unwrap_or_default().display(),
                 e
             );
             anyhow!(e)
```
Comment (gusinacio) [inline service/src/service.rs:139]: In case there's a missing config field while parsing the config file, I'd like to let the user know that it's possible to use the `--config`. Please also update `tap-agent` accordingly.

**Review by gusinacio — CHANGES_REQUESTED** [review]

**Review by gusinacio — APPROVED** [review]
LGTM

**Review by gusinacio — APPROVED** [review]
