### PR TITLE
fix: Add more information if rav request is timing out

### LINKED ISSUE #320: Add error log on RAV Request timeout
Users should know when a RAV Request is timing out and how to fix this by updating their configuration.

Probably an `inspect_err` [here](https://github.com/graphprotocol/indexer-rs/blob/c693f0ebe36a0f5dce8f46fd974eef1a5924c3c6/tap-agent/src/agent/sender_allocation.rs#L547) and a match to print this message only when you have a Timeout.

### PR DESCRIPTION
**Pull request by carlosvdr**
fixes #320

### CODE REVIEW

File: tap-agent/src/agent/sender_allocation.rs [hunk 1]
```diff
@@ -554,7 +554,18 @@ impl SenderAllocationState {
...
+                    .await
+                    .inspect_err(|err| match &err {
+                        jsonrpsee::core::ClientError::RequestTimeout => {
+                            warn!(
+                                "Rav request is timing out, maybe request_timeout_secs is too \
+                                    low in your config file, try adding more secs to the value"
+                            );
+                        }
+                        _ => {
+                            warn!("An error occured {:?}", err);
```
Comment (gusinacio) [inline tap-agent/src/agent/sender_allocation.rs:566]: you can remove this warn because it's already print it out as error somewhere else

File: tap-agent/src/agent/sender_allocation.rs [hunk 2]
```diff
@@ -554,7 +554,18 @@ impl SenderAllocationState {
                             previous_rav
                         ),
                     )
-                    .await?;
+                    .await
+                    .inspect_err(|err| match &err {
+                        jsonrpsee::core::ClientError::RequestTimeout => {
+                            warn!(
+                                "Rav request is timing out, maybe request_timeout_secs is too \
+                                    low in your config file, try adding more secs to the value"
```
Comment (gusinacio) [inline tap-agent/src/agent/sender_allocation.rs:562]: Let the user know if they already raised and it's still getting the same problem to create an issue

**Review by gusinacio — CHANGES_REQUESTED** [review]

**Review by gusinacio — APPROVED** [review]
LGTM
