### PR TITLE
fix: Add option to give either postgres_url or values individually

### LINKED ISSUE #316: Database configuration alternative
Some indexers would like to use user, password, host, port and database as an alternative to URL. 

We should provide as an alternative.

### PR DESCRIPTION
**Pull request by carlosvdr**
fixes #316

### CODE REVIEW

File: config/src/config.rs [hunk 1]
```diff
@@ -149,6 +149,11 @@ pub struct IndexerConfig {
 #[cfg_attr(test, derive(PartialEq))]
 pub struct DatabaseConfig {
     pub postgres_url: Url,
+    pub postgres_host: String,
+    pub postgres_port: i32,
+    pub postgres_user: String,
+    pub postgres_password: String,
+    pub postgress_db: String,
```
Comment (gusinacio) [inline config/src/config.rs:156]: You should turn this into an Enum with two variants: `Url { postgres_url: Url }` and `Splitten { .. }`. Also, password and port should be optional.

File: common/src/indexer_service/http/config.rs [hunk 2]
```diff
@@ -5,11 +5,42 @@ use std::net::SocketAddr;
...
 use serde::{Deserialize, Serialize};
 use thegraph_core::{Address, DeploymentId};
+use tracing::warn;
 
 #[derive(Clone, Debug, Deserialize, Serialize)]
 pub struct DatabaseConfig {
     pub postgres_url: String,
 }
+impl DatabaseConfig {
+    pub fn format_db_config(
```
Comment (gusinacio) [inline common/src/indexer_service/http/config.rs:15]: Instead of a function here, `config` should have a `get_formatted_db_url(&self)-> Url`

**Review by gusinacio — CHANGES_REQUESTED** [review]
It's also missing tap-gent configuration.

**Comment by carlosvdr** [comment]
Will fix commit from fix - > to feat but dont want to force push until you have finished reviewing

File: config/minimal-config-example.toml [hunk 3]
```diff
@@ -19,6 +19,13 @@ operator_mnemonic = "celery smart tip orange scare van steel radio dragon joy al
 # that is used by the `indexer-agent`. It is expected that `indexer-agent` will create
 # the necessary tables.
 postgres_url = "postgres://postgres@postgres:5432/postgres"
+# You can also use the following fields to specify the connection details separately.
+# either use `postgres_url` or the following fields.
+postgres_host = "postgres-host"
+postgres_port = 5432
+postgres_user = "user"
+postgres_password = "pwd"
+postgress_db = "postgres"
```
Comment (gusinacio) [inline config/minimal-config-example.toml:28]: These configs are invalid, you should set just `host`, `port`, `user`, etc.

File: config/maximal-config-example.toml [hunk 4]
```diff
@@ -33,6 +33,13 @@ port = 7300
 # that is used by the `indexer-agent`. It is expected that `indexer-agent` will create
 # the necessary tables.
 postgres_url = "postgres://postgres@postgres:5432/postgres"
+# You can also use the following fields to specify the connection details separately.
+# either use `postgres_url` or the following fields.
+postgres_host = "postgres-host"
+postgres_port = 5432
+postgres_user = "user"
+postgres_password = "pwd"
+postgress_db = "postgres"
```
Comment (gusinacio) [inline config/maximal-config-example.toml:42]: same here

File: common/src/indexer_service/http/config.rs [hunk 5]
```diff
@@ -10,7 +10,6 @@ use thegraph_core::{Address, DeploymentId};
 pub struct DatabaseConfig {
     pub postgres_url: String,
 }
-
```
Comment (gusinacio) [inline common/src/indexer_service/http/config.rs:13]: we don't need this line diff

File: config/maximal-config-example.toml (hunk 4 above)
Comment (gusinacio) [reply config/maximal-config-example.toml:42]: you could use one style in the minimal config, and another in the maximal config so that means we are testing both. Don't forget to leave the comment "as alternative you can use this other one"

File: config/src/config.rs [hunk 6]
```diff
@@ -147,8 +147,40 @@ pub struct IndexerConfig {
...
+        user: String,
+        password: Option<String>,
+        database: String,
+    },
+}
+impl DatabaseConfig {
+    pub fn get_formated_postgres_url(&self) -> Url {
+        match self {
+            DatabaseConfig::PostgresUrl { postgres_url } => postgres_url.clone(),
+            DatabaseConfig::PostgresVars {
```
Comment (gusinacio) [inline config/src/config.rs:167]: This is a little nit-picking but you can use just `self` and not clone. This is useful if you don't plan to use DatabaseConfig twice.

File: config/src/config.rs [hunk 7]
```diff
@@ -147,8 +147,40 @@ pub struct IndexerConfig {
...
+                host,
+                port,
+                user,
+                password,
+                database,
+            } => {
+                let postgres_url_str = format!("postgres://{}@{}/{}", user, host, database);
+                let mut postgres_url = Url::parse(&postgres_url_str).unwrap();
```
Comment (gusinacio) [inline config/src/config.rs:175]: Could you use expect and add a nice message here like "Failed to parse database_url".

File: config/src/config.rs [hunk 8]
```diff
@@ -147,8 +147,40 @@ pub struct IndexerConfig {
...
+                postgres_url
+                    .set_password(password.as_deref())
+                    .expect("url is wrong");
+                postgres_url.set_port(*port).expect("url is wrong");
```
Comment (gusinacio) [inline config/src/config.rs:179]: Could you add more information like: "Failed to set password" and "Failed to set port".?

**Review by gusinacio — CHANGES_REQUESTED** [review]
I loved this solution. Really elegant and uses the Rusty way. Thank you for this great code.

Here are some small nit-picks, typos and errors that I found on the documentation.

File: config/maximal-config-example.toml (hunk 4 above)
Comment (carlosvdr) [reply config/maximal-config-example.toml:42]: I prefer both having same style to make the whole thing cohesive

File: config/src/config.rs (hunk 8 above)
Comment (carlosvdr) [reply config/src/config.rs:179]: woops yes was going to add this and forgot

File: config/maximal-config-example.toml (hunk 4 above)
Comment (carlosvdr) [reply config/maximal-config-example.toml:42]: "as alternative you can use this other one", what did yopu meant by this?
There is already a comment 
```
# You can also use the following fields to specify the connection details separately.
# either use `postgres_url` or the following fields.
```

File: config/maximal-config-example.toml [hunk 9]
```diff
@@ -33,6 +33,13 @@ port = 7300
 # that is used by the `indexer-agent`. It is expected that `indexer-agent` will create
 # the necessary tables.
 postgres_url = "postgres://postgres@postgres:5432/postgres"
```
Comment (gusinacio) [inline config/maximal-config-example.toml:35]: Hey, for some reason our software doesn't have an error by having both. Could you check here https://serde.rs/container-attrs.html#deny_unknown_fields?

File: config/minimal-config-example.toml [hunk 10]
```diff
@@ -19,6 +19,13 @@ operator_mnemonic = "celery smart tip orange scare van steel radio dragon joy al
 # that is used by the `indexer-agent`. It is expected that `indexer-agent` will create
 # the necessary tables.
 postgres_url = "postgres://postgres@postgres:5432/postgres"
+# You can also use the following fields to specify the connection details separately.
```
Comment (gusinacio) [inline config/minimal-config-example.toml:22]: I understand you wanting to keep the same on both. Could you create a test if we have a `toml string` with the splitten config it's generating the expected PostgresVars variant?

**Review by gusinacio — CHANGES_REQUESTED** [review]

**Review by gusinacio — APPROVED** [review]
LGTM
